field.value.cults3d_embed:
  type: mapping
  label: Default value
  mapping:
    url:
      type: string
      label: URL
    model_id:
      type: string
      label: Model ID
    cache_timestamp:
      type: integer
      label: Timestamp

cults3d_embed.settings:
  type: config_object
  label: 'Cults3d embed settings'
  mapping:
    api_key:
      type: string
      label: 'API Key'